// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "rgb2yuv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic rgb2yuv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic rgb2yuv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> rgb2yuv::ap_ST_fsm_state1 = "1";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state2 = "10";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state3 = "100";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state4 = "1000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state5 = "10000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state6 = "100000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> rgb2yuv::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> rgb2yuv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> rgb2yuv::ap_const_lv32_1 = "1";
const sc_lv<1> rgb2yuv::ap_const_lv1_0 = "0";
const sc_lv<32> rgb2yuv::ap_const_lv32_2 = "10";
const sc_lv<32> rgb2yuv::ap_const_lv32_5 = "101";
const sc_lv<32> rgb2yuv::ap_const_lv32_6 = "110";
const sc_lv<32> rgb2yuv::ap_const_lv32_7 = "111";
const sc_lv<32> rgb2yuv::ap_const_lv32_8 = "1000";
const sc_lv<16> rgb2yuv::ap_const_lv16_0 = "0000000000000000";
const sc_lv<1> rgb2yuv::ap_const_lv1_1 = "1";
const sc_lv<32> rgb2yuv::ap_const_lv32_9 = "1001";
const sc_lv<32> rgb2yuv::ap_const_lv32_3 = "11";
const sc_lv<32> rgb2yuv::ap_const_lv32_4 = "100";
const sc_lv<16> rgb2yuv::ap_const_lv16_1 = "1";
const sc_lv<10> rgb2yuv::ap_const_lv10_0 = "0000000000";
const sc_lv<8> rgb2yuv::ap_const_lv8_0 = "00000000";
const sc_lv<9> rgb2yuv::ap_const_lv9_80 = "10000000";
const sc_lv<6> rgb2yuv::ap_const_lv6_0 = "000000";
const sc_lv<7> rgb2yuv::ap_const_lv7_0 = "0000000";
const sc_lv<32> rgb2yuv::ap_const_lv32_F = "1111";
const sc_lv<16> rgb2yuv::ap_const_lv16_FFB6 = "1111111110110110";
const sc_lv<4> rgb2yuv::ap_const_lv4_0 = "0000";
const sc_lv<16> rgb2yuv::ap_const_lv16_7A = "1111010";
const sc_lv<13> rgb2yuv::ap_const_lv13_0 = "0000000000000";
const sc_lv<14> rgb2yuv::ap_const_lv14_80 = "10000000";
const sc_lv<8> rgb2yuv::ap_const_lv8_10 = "10000";
const sc_lv<16> rgb2yuv::ap_const_lv16_80 = "10000000";
const sc_lv<8> rgb2yuv::ap_const_lv8_80 = "10000000";
const sc_lv<13> rgb2yuv::ap_const_lv13_19 = "11001";
const sc_lv<15> rgb2yuv::ap_const_lv15_7FDA = "111111111011010";
const sc_lv<16> rgb2yuv::ap_const_lv16_FFA2 = "1111111110100010";
const bool rgb2yuv::ap_const_boolean_1 = true;

rgb2yuv::rgb2yuv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    yuv_filter_mac_mubkb_U0 = new yuv_filter_mac_mubkb<1,1,8,6,9,13>("yuv_filter_mac_mubkb_U0");
    yuv_filter_mac_mubkb_U0->din0(grp_fu_512_p0);
    yuv_filter_mac_mubkb_U0->din1(grp_fu_512_p1);
    yuv_filter_mac_mubkb_U0->din2(grp_fu_512_p2);
    yuv_filter_mac_mubkb_U0->dout(grp_fu_512_p3);
    yuv_filter_mac_mucud_U1 = new yuv_filter_mac_mucud<1,1,8,7,16,16>("yuv_filter_mac_mucud_U1");
    yuv_filter_mac_mucud_U1->din0(grp_fu_521_p0);
    yuv_filter_mac_mucud_U1->din1(grp_fu_521_p1);
    yuv_filter_mac_mucud_U1->din2(tmp_29_reg_628);
    yuv_filter_mac_mucud_U1->dout(grp_fu_521_p3);
    yuv_filter_mac_mudEe_U2 = new yuv_filter_mac_mudEe<1,1,8,8,16,16>("yuv_filter_mac_mudEe_U2");
    yuv_filter_mac_mudEe_U2->din0(grp_fu_529_p0);
    yuv_filter_mac_mudEe_U2->din1(grp_fu_529_p1);
    yuv_filter_mac_mudEe_U2->din2(tmp_33_reg_638);
    yuv_filter_mac_mudEe_U2->dout(grp_fu_529_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_208_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_208_p2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_208_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_208_p2 );

    SC_METHOD(thread_exitcond1_fu_208_p2);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_reg_186 );

    SC_METHOD(thread_exitcond_fu_259_p2);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_reg_197 );

    SC_METHOD(thread_grp_fu_512_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_512_p00 );

    SC_METHOD(thread_grp_fu_512_p00);
    sensitive << ( B_reg_605 );

    SC_METHOD(thread_grp_fu_512_p1);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_512_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_512_p20 );

    SC_METHOD(thread_grp_fu_512_p20);
    sensitive << ( tmp4_reg_613 );

    SC_METHOD(thread_grp_fu_521_p0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_fu_521_p00 );

    SC_METHOD(thread_grp_fu_521_p00);
    sensitive << ( R_reg_591 );

    SC_METHOD(thread_grp_fu_521_p1);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_529_p0);
    sensitive << ( tmp_35_cast1_reg_618 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_529_p1);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_in_channels_ch1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_24_cast_fu_279_p1 );

    SC_METHOD(thread_in_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch2_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_24_cast_fu_279_p1 );

    SC_METHOD(thread_in_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch3_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_24_cast_fu_279_p1 );

    SC_METHOD(thread_in_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_out_channels_ch1_address0);
    sensitive << ( tmp_24_cast_reg_569 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_out_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch1_d0);
    sensitive << ( tmp_27_reg_623 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_out_channels_ch1_we0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_out_channels_ch2_address0);
    sensitive << ( tmp_24_cast_reg_569 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch2_d0);
    sensitive << ( tmp_32_reg_658 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_address0);
    sensitive << ( tmp_24_cast_reg_569 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch3_d0);
    sensitive << ( tmp_37_reg_663 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_p_neg_cast_fu_426_p1);
    sensitive << ( p_neg_fu_420_p2 );

    SC_METHOD(thread_p_neg_fu_420_p2);
    sensitive << ( p_shl3_cast9_fu_400_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_437_p1);
    sensitive << ( p_shl1_fu_430_p3 );

    SC_METHOD(thread_p_shl1_fu_430_p3);
    sensitive << ( B_reg_605 );

    SC_METHOD(thread_p_shl2_cast_fu_389_p1);
    sensitive << ( p_shl2_fu_382_p3 );

    SC_METHOD(thread_p_shl2_fu_382_p3);
    sensitive << ( B_reg_605 );

    SC_METHOD(thread_p_shl3_cast9_fu_400_p1);
    sensitive << ( p_shl3_fu_393_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_404_p1);
    sensitive << ( p_shl3_fu_393_p3 );

    SC_METHOD(thread_p_shl3_fu_393_p3);
    sensitive << ( B_reg_605 );

    SC_METHOD(thread_p_shl4_cast_fu_331_p1);
    sensitive << ( p_shl4_fu_324_p3 );

    SC_METHOD(thread_p_shl4_fu_324_p3);
    sensitive << ( G_reg_599 );

    SC_METHOD(thread_p_shl5_cast_fu_306_p1);
    sensitive << ( p_shl5_fu_299_p3 );

    SC_METHOD(thread_p_shl5_fu_299_p3);
    sensitive << ( R_reg_591 );

    SC_METHOD(thread_p_shl6_cast_fu_317_p1);
    sensitive << ( p_shl6_fu_310_p3 );

    SC_METHOD(thread_p_shl6_fu_310_p3);
    sensitive << ( R_reg_591 );

    SC_METHOD(thread_p_shl7_cast_fu_235_p3);
    sensitive << ( tmp_21_fu_231_p1 );

    SC_METHOD(thread_p_shl_cast_fu_223_p3);
    sensitive << ( tmp_fu_219_p1 );

    SC_METHOD(thread_tmp1_fu_348_p2);
    sensitive << ( tmp2_cast_fu_344_p1 );
    sensitive << ( p_shl4_cast_fu_331_p1 );

    SC_METHOD(thread_tmp2_cast_fu_344_p1);
    sensitive << ( tmp2_fu_338_p2 );

    SC_METHOD(thread_tmp2_fu_338_p2);
    sensitive << ( p_shl6_cast_fu_317_p1 );
    sensitive << ( p_shl5_cast_fu_306_p1 );

    SC_METHOD(thread_tmp3_cast_fu_357_p1);
    sensitive << ( grp_fu_512_p3 );

    SC_METHOD(thread_tmp4_fu_290_p2);
    sensitive << ( tmp_35_cast2_fu_286_p1 );

    SC_METHOD(thread_tmp6_fu_462_p2);
    sensitive << ( tmp_30_reg_633 );

    SC_METHOD(thread_tmp8_cast_fu_482_p1);
    sensitive << ( tmp8_reg_643 );

    SC_METHOD(thread_tmp8_fu_447_p2);
    sensitive << ( tmp_35_fu_441_p2 );

    SC_METHOD(thread_tmp_21_fu_231_p1);
    sensitive << ( x_reg_186 );

    SC_METHOD(thread_tmp_22_fu_243_p2);
    sensitive << ( p_shl_cast_fu_223_p3 );
    sensitive << ( p_shl7_cast_fu_235_p3 );

    SC_METHOD(thread_tmp_24_cast_fu_279_p1);
    sensitive << ( tmp_24_fu_274_p2 );

    SC_METHOD(thread_tmp_24_fu_274_p2);
    sensitive << ( tmp_22_reg_556 );
    sensitive << ( tmp_cast_fu_270_p1 );

    SC_METHOD(thread_tmp_26_fu_360_p2);
    sensitive << ( tmp3_cast_fu_357_p1 );
    sensitive << ( tmp1_fu_348_p2 );

    SC_METHOD(thread_tmp_29_fu_376_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_29_fu_376_p00 );

    SC_METHOD(thread_tmp_29_fu_376_p00);
    sensitive << ( G_reg_599 );

    SC_METHOD(thread_tmp_29_fu_376_p2);
    sensitive << ( tmp_29_fu_376_p0 );

    SC_METHOD(thread_tmp_30_fu_408_p2);
    sensitive << ( p_shl2_cast_fu_389_p1 );
    sensitive << ( p_shl3_cast_fu_404_p1 );

    SC_METHOD(thread_tmp_31_fu_467_p2);
    sensitive << ( tmp6_fu_462_p2 );
    sensitive << ( grp_fu_521_p3 );

    SC_METHOD(thread_tmp_33_fu_414_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_33_fu_414_p00 );

    SC_METHOD(thread_tmp_33_fu_414_p00);
    sensitive << ( R_reg_591 );

    SC_METHOD(thread_tmp_33_fu_414_p2);
    sensitive << ( tmp_33_fu_414_p0 );

    SC_METHOD(thread_tmp_35_cast1_fu_321_p1);
    sensitive << ( G_reg_599 );

    SC_METHOD(thread_tmp_35_cast2_fu_286_p1);
    sensitive << ( in_channels_ch2_q0 );

    SC_METHOD(thread_tmp_35_fu_441_p2);
    sensitive << ( p_neg_cast_fu_426_p1 );
    sensitive << ( p_shl1_cast_fu_437_p1 );

    SC_METHOD(thread_tmp_36_fu_485_p2);
    sensitive << ( tmp8_cast_fu_482_p1 );
    sensitive << ( grp_fu_529_p3 );

    SC_METHOD(thread_tmp_cast_fu_270_p1);
    sensitive << ( y_reg_197 );

    SC_METHOD(thread_tmp_fu_219_p1);
    sensitive << ( x_reg_186 );

    SC_METHOD(thread_x_2_fu_213_p2);
    sensitive << ( x_reg_186 );

    SC_METHOD(thread_y_2_fu_264_p2);
    sensitive << ( y_reg_197 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_208_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_259_p2 );

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "rgb2yuv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_channels_ch1_address0, "(port)in_channels_ch1_address0");
    sc_trace(mVcdFile, in_channels_ch1_ce0, "(port)in_channels_ch1_ce0");
    sc_trace(mVcdFile, in_channels_ch1_q0, "(port)in_channels_ch1_q0");
    sc_trace(mVcdFile, in_channels_ch2_address0, "(port)in_channels_ch2_address0");
    sc_trace(mVcdFile, in_channels_ch2_ce0, "(port)in_channels_ch2_ce0");
    sc_trace(mVcdFile, in_channels_ch2_q0, "(port)in_channels_ch2_q0");
    sc_trace(mVcdFile, in_channels_ch3_address0, "(port)in_channels_ch3_address0");
    sc_trace(mVcdFile, in_channels_ch3_ce0, "(port)in_channels_ch3_ce0");
    sc_trace(mVcdFile, in_channels_ch3_q0, "(port)in_channels_ch3_q0");
    sc_trace(mVcdFile, in_width_read, "(port)in_width_read");
    sc_trace(mVcdFile, in_height_read, "(port)in_height_read");
    sc_trace(mVcdFile, out_channels_ch1_address0, "(port)out_channels_ch1_address0");
    sc_trace(mVcdFile, out_channels_ch1_ce0, "(port)out_channels_ch1_ce0");
    sc_trace(mVcdFile, out_channels_ch1_we0, "(port)out_channels_ch1_we0");
    sc_trace(mVcdFile, out_channels_ch1_d0, "(port)out_channels_ch1_d0");
    sc_trace(mVcdFile, out_channels_ch2_address0, "(port)out_channels_ch2_address0");
    sc_trace(mVcdFile, out_channels_ch2_ce0, "(port)out_channels_ch2_ce0");
    sc_trace(mVcdFile, out_channels_ch2_we0, "(port)out_channels_ch2_we0");
    sc_trace(mVcdFile, out_channels_ch2_d0, "(port)out_channels_ch2_d0");
    sc_trace(mVcdFile, out_channels_ch3_address0, "(port)out_channels_ch3_address0");
    sc_trace(mVcdFile, out_channels_ch3_ce0, "(port)out_channels_ch3_ce0");
    sc_trace(mVcdFile, out_channels_ch3_we0, "(port)out_channels_ch3_we0");
    sc_trace(mVcdFile, out_channels_ch3_d0, "(port)out_channels_ch3_d0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, x_2_fu_213_p2, "x_2_fu_213_p2");
    sc_trace(mVcdFile, x_2_reg_551, "x_2_reg_551");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_22_fu_243_p2, "tmp_22_fu_243_p2");
    sc_trace(mVcdFile, tmp_22_reg_556, "tmp_22_reg_556");
    sc_trace(mVcdFile, exitcond1_fu_208_p2, "exitcond1_fu_208_p2");
    sc_trace(mVcdFile, y_2_fu_264_p2, "y_2_fu_264_p2");
    sc_trace(mVcdFile, y_2_reg_564, "y_2_reg_564");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_24_cast_fu_279_p1, "tmp_24_cast_fu_279_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_569, "tmp_24_cast_reg_569");
    sc_trace(mVcdFile, exitcond_fu_259_p2, "exitcond_fu_259_p2");
    sc_trace(mVcdFile, R_reg_591, "R_reg_591");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, G_reg_599, "G_reg_599");
    sc_trace(mVcdFile, B_reg_605, "B_reg_605");
    sc_trace(mVcdFile, tmp4_fu_290_p2, "tmp4_fu_290_p2");
    sc_trace(mVcdFile, tmp4_reg_613, "tmp4_reg_613");
    sc_trace(mVcdFile, tmp_35_cast1_fu_321_p1, "tmp_35_cast1_fu_321_p1");
    sc_trace(mVcdFile, tmp_35_cast1_reg_618, "tmp_35_cast1_reg_618");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_27_reg_623, "tmp_27_reg_623");
    sc_trace(mVcdFile, tmp_29_fu_376_p2, "tmp_29_fu_376_p2");
    sc_trace(mVcdFile, tmp_29_reg_628, "tmp_29_reg_628");
    sc_trace(mVcdFile, tmp_30_fu_408_p2, "tmp_30_fu_408_p2");
    sc_trace(mVcdFile, tmp_30_reg_633, "tmp_30_reg_633");
    sc_trace(mVcdFile, tmp_33_fu_414_p2, "tmp_33_fu_414_p2");
    sc_trace(mVcdFile, tmp_33_reg_638, "tmp_33_reg_638");
    sc_trace(mVcdFile, tmp8_fu_447_p2, "tmp8_fu_447_p2");
    sc_trace(mVcdFile, tmp8_reg_643, "tmp8_reg_643");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_32_reg_658, "tmp_32_reg_658");
    sc_trace(mVcdFile, tmp_37_reg_663, "tmp_37_reg_663");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, x_reg_186, "x_reg_186");
    sc_trace(mVcdFile, y_reg_197, "y_reg_197");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_fu_219_p1, "tmp_fu_219_p1");
    sc_trace(mVcdFile, tmp_21_fu_231_p1, "tmp_21_fu_231_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_223_p3, "p_shl_cast_fu_223_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_235_p3, "p_shl7_cast_fu_235_p3");
    sc_trace(mVcdFile, tmp_cast_fu_270_p1, "tmp_cast_fu_270_p1");
    sc_trace(mVcdFile, tmp_24_fu_274_p2, "tmp_24_fu_274_p2");
    sc_trace(mVcdFile, tmp_35_cast2_fu_286_p1, "tmp_35_cast2_fu_286_p1");
    sc_trace(mVcdFile, p_shl5_fu_299_p3, "p_shl5_fu_299_p3");
    sc_trace(mVcdFile, p_shl6_fu_310_p3, "p_shl6_fu_310_p3");
    sc_trace(mVcdFile, p_shl4_fu_324_p3, "p_shl4_fu_324_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_317_p1, "p_shl6_cast_fu_317_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_306_p1, "p_shl5_cast_fu_306_p1");
    sc_trace(mVcdFile, tmp2_fu_338_p2, "tmp2_fu_338_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_344_p1, "tmp2_cast_fu_344_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_331_p1, "p_shl4_cast_fu_331_p1");
    sc_trace(mVcdFile, grp_fu_512_p3, "grp_fu_512_p3");
    sc_trace(mVcdFile, tmp3_cast_fu_357_p1, "tmp3_cast_fu_357_p1");
    sc_trace(mVcdFile, tmp1_fu_348_p2, "tmp1_fu_348_p2");
    sc_trace(mVcdFile, tmp_26_fu_360_p2, "tmp_26_fu_360_p2");
    sc_trace(mVcdFile, tmp_29_fu_376_p0, "tmp_29_fu_376_p0");
    sc_trace(mVcdFile, p_shl2_fu_382_p3, "p_shl2_fu_382_p3");
    sc_trace(mVcdFile, p_shl3_fu_393_p3, "p_shl3_fu_393_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_389_p1, "p_shl2_cast_fu_389_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_404_p1, "p_shl3_cast_fu_404_p1");
    sc_trace(mVcdFile, tmp_33_fu_414_p0, "tmp_33_fu_414_p0");
    sc_trace(mVcdFile, p_shl3_cast9_fu_400_p1, "p_shl3_cast9_fu_400_p1");
    sc_trace(mVcdFile, p_neg_fu_420_p2, "p_neg_fu_420_p2");
    sc_trace(mVcdFile, p_shl1_fu_430_p3, "p_shl1_fu_430_p3");
    sc_trace(mVcdFile, p_neg_cast_fu_426_p1, "p_neg_cast_fu_426_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_437_p1, "p_shl1_cast_fu_437_p1");
    sc_trace(mVcdFile, tmp_35_fu_441_p2, "tmp_35_fu_441_p2");
    sc_trace(mVcdFile, tmp6_fu_462_p2, "tmp6_fu_462_p2");
    sc_trace(mVcdFile, grp_fu_521_p3, "grp_fu_521_p3");
    sc_trace(mVcdFile, tmp_31_fu_467_p2, "tmp_31_fu_467_p2");
    sc_trace(mVcdFile, tmp8_cast_fu_482_p1, "tmp8_cast_fu_482_p1");
    sc_trace(mVcdFile, grp_fu_529_p3, "grp_fu_529_p3");
    sc_trace(mVcdFile, tmp_36_fu_485_p2, "tmp_36_fu_485_p2");
    sc_trace(mVcdFile, grp_fu_512_p0, "grp_fu_512_p0");
    sc_trace(mVcdFile, grp_fu_512_p1, "grp_fu_512_p1");
    sc_trace(mVcdFile, grp_fu_512_p2, "grp_fu_512_p2");
    sc_trace(mVcdFile, grp_fu_521_p0, "grp_fu_521_p0");
    sc_trace(mVcdFile, grp_fu_521_p1, "grp_fu_521_p1");
    sc_trace(mVcdFile, grp_fu_529_p0, "grp_fu_529_p0");
    sc_trace(mVcdFile, grp_fu_529_p1, "grp_fu_529_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_512_p00, "grp_fu_512_p00");
    sc_trace(mVcdFile, grp_fu_512_p20, "grp_fu_512_p20");
    sc_trace(mVcdFile, grp_fu_521_p00, "grp_fu_521_p00");
    sc_trace(mVcdFile, tmp_29_fu_376_p00, "tmp_29_fu_376_p00");
    sc_trace(mVcdFile, tmp_33_fu_414_p00, "tmp_33_fu_414_p00");
#endif

    }
}

rgb2yuv::~rgb2yuv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete yuv_filter_mac_mubkb_U0;
    delete yuv_filter_mac_mucud_U1;
    delete yuv_filter_mac_mudEe_U2;
}

void rgb2yuv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_1))) {
        x_reg_186 = x_2_reg_551.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_reg_186 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        y_reg_197 = y_2_reg_564.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_208_p2.read(), ap_const_lv1_0))) {
        y_reg_197 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_reg_605 = in_channels_ch3_q0.read();
        G_reg_599 = in_channels_ch2_q0.read();
        R_reg_591 = in_channels_ch1_q0.read();
        tmp4_reg_613 = tmp4_fu_290_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp8_reg_643 = tmp8_fu_447_p2.read();
        tmp_27_reg_623 = tmp_26_fu_360_p2.read().range(15, 8);
        tmp_29_reg_628 = tmp_29_fu_376_p2.read();
        tmp_30_reg_633 = tmp_30_fu_408_p2.read();
        tmp_33_reg_638 = tmp_33_fu_414_p2.read();
        tmp_35_cast1_reg_618 = tmp_35_cast1_fu_321_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_208_p2.read(), ap_const_lv1_0))) {
        tmp_22_reg_556 = tmp_22_fu_243_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_259_p2.read()))) {
        tmp_24_cast_reg_569 = tmp_24_cast_fu_279_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_32_reg_658 = tmp_31_fu_467_p2.read().range(15, 8);
        tmp_37_reg_663 = tmp_36_fu_485_p2.read().range(15, 8);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_2_reg_551 = x_2_fu_213_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_2_reg_564 = y_2_fu_264_p2.read();
    }
}

void rgb2yuv::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void rgb2yuv::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void rgb2yuv::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void rgb2yuv::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void rgb2yuv::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void rgb2yuv::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void rgb2yuv::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void rgb2yuv::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void rgb2yuv::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void rgb2yuv::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void rgb2yuv::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_208_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void rgb2yuv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void rgb2yuv::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_208_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void rgb2yuv::thread_ap_return_0() {
    ap_return_0 = in_width_read.read();
}

void rgb2yuv::thread_ap_return_1() {
    ap_return_1 = in_height_read.read();
}

void rgb2yuv::thread_exitcond1_fu_208_p2() {
    exitcond1_fu_208_p2 = (!x_reg_186.read().is_01() || !in_width_read.read().is_01())? sc_lv<1>(): sc_lv<1>(x_reg_186.read() == in_width_read.read());
}

void rgb2yuv::thread_exitcond_fu_259_p2() {
    exitcond_fu_259_p2 = (!y_reg_197.read().is_01() || !in_height_read.read().is_01())? sc_lv<1>(): sc_lv<1>(y_reg_197.read() == in_height_read.read());
}

void rgb2yuv::thread_grp_fu_512_p0() {
    grp_fu_512_p0 =  (sc_lv<8>) (grp_fu_512_p00.read());
}

void rgb2yuv::thread_grp_fu_512_p00() {
    grp_fu_512_p00 = esl_zext<13,8>(B_reg_605.read());
}

void rgb2yuv::thread_grp_fu_512_p1() {
    grp_fu_512_p1 =  (sc_lv<6>) (ap_const_lv13_19);
}

void rgb2yuv::thread_grp_fu_512_p2() {
    grp_fu_512_p2 =  (sc_lv<9>) (grp_fu_512_p20.read());
}

void rgb2yuv::thread_grp_fu_512_p20() {
    grp_fu_512_p20 = esl_zext<13,9>(tmp4_reg_613.read());
}

void rgb2yuv::thread_grp_fu_521_p0() {
    grp_fu_521_p0 =  (sc_lv<8>) (grp_fu_521_p00.read());
}

void rgb2yuv::thread_grp_fu_521_p00() {
    grp_fu_521_p00 = esl_zext<15,8>(R_reg_591.read());
}

void rgb2yuv::thread_grp_fu_521_p1() {
    grp_fu_521_p1 =  (sc_lv<7>) (ap_const_lv15_7FDA);
}

void rgb2yuv::thread_grp_fu_529_p0() {
    grp_fu_529_p0 =  (sc_lv<8>) (tmp_35_cast1_reg_618.read());
}

void rgb2yuv::thread_grp_fu_529_p1() {
    grp_fu_529_p1 =  (sc_lv<8>) (ap_const_lv16_FFA2);
}

void rgb2yuv::thread_in_channels_ch1_address0() {
    in_channels_ch1_address0 =  (sc_lv<22>) (tmp_24_cast_fu_279_p1.read());
}

void rgb2yuv::thread_in_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_in_channels_ch2_address0() {
    in_channels_ch2_address0 =  (sc_lv<22>) (tmp_24_cast_fu_279_p1.read());
}

void rgb2yuv::thread_in_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_in_channels_ch3_address0() {
    in_channels_ch3_address0 =  (sc_lv<22>) (tmp_24_cast_fu_279_p1.read());
}

void rgb2yuv::thread_in_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch1_address0() {
    out_channels_ch1_address0 =  (sc_lv<22>) (tmp_24_cast_reg_569.read());
}

void rgb2yuv::thread_out_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        out_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch1_d0() {
    out_channels_ch1_d0 = (!tmp_27_reg_623.read().is_01() || !ap_const_lv8_10.is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_27_reg_623.read()) + sc_biguint<8>(ap_const_lv8_10));
}

void rgb2yuv::thread_out_channels_ch1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        out_channels_ch1_we0 = ap_const_logic_1;
    } else {
        out_channels_ch1_we0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch2_address0() {
    out_channels_ch2_address0 =  (sc_lv<22>) (tmp_24_cast_reg_569.read());
}

void rgb2yuv::thread_out_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch2_d0() {
    out_channels_ch2_d0 = (tmp_32_reg_658.read() ^ ap_const_lv8_80);
}

void rgb2yuv::thread_out_channels_ch2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch2_we0 = ap_const_logic_1;
    } else {
        out_channels_ch2_we0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch3_address0() {
    out_channels_ch3_address0 =  (sc_lv<22>) (tmp_24_cast_reg_569.read());
}

void rgb2yuv::thread_out_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_out_channels_ch3_d0() {
    out_channels_ch3_d0 = (tmp_37_reg_663.read() ^ ap_const_lv8_80);
}

void rgb2yuv::thread_out_channels_ch3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch3_we0 = ap_const_logic_1;
    } else {
        out_channels_ch3_we0 = ap_const_logic_0;
    }
}

void rgb2yuv::thread_p_neg_cast_fu_426_p1() {
    p_neg_cast_fu_426_p1 = esl_sext<14,13>(p_neg_fu_420_p2.read());
}

void rgb2yuv::thread_p_neg_fu_420_p2() {
    p_neg_fu_420_p2 = (!ap_const_lv13_0.is_01() || !p_shl3_cast9_fu_400_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(p_shl3_cast9_fu_400_p1.read()));
}

void rgb2yuv::thread_p_shl1_cast_fu_437_p1() {
    p_shl1_cast_fu_437_p1 = esl_zext<14,9>(p_shl1_fu_430_p3.read());
}

void rgb2yuv::thread_p_shl1_fu_430_p3() {
    p_shl1_fu_430_p3 = esl_concat<8,1>(B_reg_605.read(), ap_const_lv1_0);
}

void rgb2yuv::thread_p_shl2_cast_fu_389_p1() {
    p_shl2_cast_fu_389_p1 = esl_zext<16,15>(p_shl2_fu_382_p3.read());
}

void rgb2yuv::thread_p_shl2_fu_382_p3() {
    p_shl2_fu_382_p3 = esl_concat<8,7>(B_reg_605.read(), ap_const_lv7_0);
}

void rgb2yuv::thread_p_shl3_cast9_fu_400_p1() {
    p_shl3_cast9_fu_400_p1 = esl_zext<13,12>(p_shl3_fu_393_p3.read());
}

void rgb2yuv::thread_p_shl3_cast_fu_404_p1() {
    p_shl3_cast_fu_404_p1 = esl_zext<16,12>(p_shl3_fu_393_p3.read());
}

void rgb2yuv::thread_p_shl3_fu_393_p3() {
    p_shl3_fu_393_p3 = esl_concat<8,4>(B_reg_605.read(), ap_const_lv4_0);
}

void rgb2yuv::thread_p_shl4_cast_fu_331_p1() {
    p_shl4_cast_fu_331_p1 = esl_zext<16,15>(p_shl4_fu_324_p3.read());
}

void rgb2yuv::thread_p_shl4_fu_324_p3() {
    p_shl4_fu_324_p3 = esl_concat<8,7>(G_reg_599.read(), ap_const_lv7_0);
}

void rgb2yuv::thread_p_shl5_cast_fu_306_p1() {
    p_shl5_cast_fu_306_p1 = esl_zext<15,14>(p_shl5_fu_299_p3.read());
}

void rgb2yuv::thread_p_shl5_fu_299_p3() {
    p_shl5_fu_299_p3 = esl_concat<8,6>(R_reg_591.read(), ap_const_lv6_0);
}

void rgb2yuv::thread_p_shl6_cast_fu_317_p1() {
    p_shl6_cast_fu_317_p1 = esl_zext<15,9>(p_shl6_fu_310_p3.read());
}

void rgb2yuv::thread_p_shl6_fu_310_p3() {
    p_shl6_fu_310_p3 = esl_concat<8,1>(R_reg_591.read(), ap_const_lv1_0);
}

void rgb2yuv::thread_p_shl7_cast_fu_235_p3() {
    p_shl7_cast_fu_235_p3 = esl_concat<15,8>(tmp_21_fu_231_p1.read(), ap_const_lv8_0);
}

void rgb2yuv::thread_p_shl_cast_fu_223_p3() {
    p_shl_cast_fu_223_p3 = esl_concat<13,10>(tmp_fu_219_p1.read(), ap_const_lv10_0);
}

void rgb2yuv::thread_tmp1_fu_348_p2() {
    tmp1_fu_348_p2 = (!tmp2_cast_fu_344_p1.read().is_01() || !p_shl4_cast_fu_331_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp2_cast_fu_344_p1.read()) + sc_biguint<16>(p_shl4_cast_fu_331_p1.read()));
}

void rgb2yuv::thread_tmp2_cast_fu_344_p1() {
    tmp2_cast_fu_344_p1 = esl_zext<16,15>(tmp2_fu_338_p2.read());
}

void rgb2yuv::thread_tmp2_fu_338_p2() {
    tmp2_fu_338_p2 = (!p_shl6_cast_fu_317_p1.read().is_01() || !p_shl5_cast_fu_306_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl6_cast_fu_317_p1.read()) + sc_biguint<15>(p_shl5_cast_fu_306_p1.read()));
}

void rgb2yuv::thread_tmp3_cast_fu_357_p1() {
    tmp3_cast_fu_357_p1 = esl_zext<16,13>(grp_fu_512_p3.read());
}

void rgb2yuv::thread_tmp4_fu_290_p2() {
    tmp4_fu_290_p2 = (!tmp_35_cast2_fu_286_p1.read().is_01() || !ap_const_lv9_80.is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_35_cast2_fu_286_p1.read()) + sc_biguint<9>(ap_const_lv9_80));
}

void rgb2yuv::thread_tmp6_fu_462_p2() {
    tmp6_fu_462_p2 = (!tmp_30_reg_633.read().is_01() || !ap_const_lv16_80.is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_30_reg_633.read()) + sc_biguint<16>(ap_const_lv16_80));
}

void rgb2yuv::thread_tmp8_cast_fu_482_p1() {
    tmp8_cast_fu_482_p1 = esl_sext<16,14>(tmp8_reg_643.read());
}

void rgb2yuv::thread_tmp8_fu_447_p2() {
    tmp8_fu_447_p2 = (!tmp_35_fu_441_p2.read().is_01() || !ap_const_lv14_80.is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_35_fu_441_p2.read()) + sc_biguint<14>(ap_const_lv14_80));
}

void rgb2yuv::thread_tmp_21_fu_231_p1() {
    tmp_21_fu_231_p1 = x_reg_186.read().range(15-1, 0);
}

void rgb2yuv::thread_tmp_22_fu_243_p2() {
    tmp_22_fu_243_p2 = (!p_shl_cast_fu_223_p3.read().is_01() || !p_shl7_cast_fu_235_p3.read().is_01())? sc_lv<23>(): (sc_biguint<23>(p_shl_cast_fu_223_p3.read()) + sc_biguint<23>(p_shl7_cast_fu_235_p3.read()));
}

void rgb2yuv::thread_tmp_24_cast_fu_279_p1() {
    tmp_24_cast_fu_279_p1 = esl_zext<32,23>(tmp_24_fu_274_p2.read());
}

void rgb2yuv::thread_tmp_24_fu_274_p2() {
    tmp_24_fu_274_p2 = (!tmp_cast_fu_270_p1.read().is_01() || !tmp_22_reg_556.read().is_01())? sc_lv<23>(): (sc_biguint<23>(tmp_cast_fu_270_p1.read()) + sc_biguint<23>(tmp_22_reg_556.read()));
}

void rgb2yuv::thread_tmp_26_fu_360_p2() {
    tmp_26_fu_360_p2 = (!tmp3_cast_fu_357_p1.read().is_01() || !tmp1_fu_348_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp3_cast_fu_357_p1.read()) + sc_biguint<16>(tmp1_fu_348_p2.read()));
}

void rgb2yuv::thread_tmp_29_fu_376_p0() {
    tmp_29_fu_376_p0 =  (sc_lv<8>) (tmp_29_fu_376_p00.read());
}

void rgb2yuv::thread_tmp_29_fu_376_p00() {
    tmp_29_fu_376_p00 = esl_zext<16,8>(G_reg_599.read());
}

void rgb2yuv::thread_tmp_29_fu_376_p2() {
    tmp_29_fu_376_p2 = (!tmp_29_fu_376_p0.read().is_01() || !ap_const_lv16_FFB6.is_01())? sc_lv<16>(): sc_biguint<8>(tmp_29_fu_376_p0.read()) * sc_bigint<16>(ap_const_lv16_FFB6);
}

void rgb2yuv::thread_tmp_30_fu_408_p2() {
    tmp_30_fu_408_p2 = (!p_shl2_cast_fu_389_p1.read().is_01() || !p_shl3_cast_fu_404_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_shl2_cast_fu_389_p1.read()) - sc_biguint<16>(p_shl3_cast_fu_404_p1.read()));
}

void rgb2yuv::thread_tmp_31_fu_467_p2() {
    tmp_31_fu_467_p2 = (!tmp6_fu_462_p2.read().is_01() || !grp_fu_521_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp6_fu_462_p2.read()) + sc_bigint<16>(grp_fu_521_p3.read()));
}

void rgb2yuv::thread_tmp_33_fu_414_p0() {
    tmp_33_fu_414_p0 =  (sc_lv<8>) (tmp_33_fu_414_p00.read());
}

void rgb2yuv::thread_tmp_33_fu_414_p00() {
    tmp_33_fu_414_p00 = esl_zext<16,8>(R_reg_591.read());
}

void rgb2yuv::thread_tmp_33_fu_414_p2() {
    tmp_33_fu_414_p2 = (!tmp_33_fu_414_p0.read().is_01() || !ap_const_lv16_7A.is_01())? sc_lv<16>(): sc_biguint<8>(tmp_33_fu_414_p0.read()) * sc_biguint<16>(ap_const_lv16_7A);
}

void rgb2yuv::thread_tmp_35_cast1_fu_321_p1() {
    tmp_35_cast1_fu_321_p1 = esl_zext<16,8>(G_reg_599.read());
}

void rgb2yuv::thread_tmp_35_cast2_fu_286_p1() {
    tmp_35_cast2_fu_286_p1 = esl_zext<9,8>(in_channels_ch2_q0.read());
}

void rgb2yuv::thread_tmp_35_fu_441_p2() {
    tmp_35_fu_441_p2 = (!p_neg_cast_fu_426_p1.read().is_01() || !p_shl1_cast_fu_437_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(p_neg_cast_fu_426_p1.read()) - sc_biguint<14>(p_shl1_cast_fu_437_p1.read()));
}

void rgb2yuv::thread_tmp_36_fu_485_p2() {
    tmp_36_fu_485_p2 = (!tmp8_cast_fu_482_p1.read().is_01() || !grp_fu_529_p3.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp8_cast_fu_482_p1.read()) + sc_bigint<16>(grp_fu_529_p3.read()));
}

void rgb2yuv::thread_tmp_cast_fu_270_p1() {
    tmp_cast_fu_270_p1 = esl_zext<23,16>(y_reg_197.read());
}

void rgb2yuv::thread_tmp_fu_219_p1() {
    tmp_fu_219_p1 = x_reg_186.read().range(13-1, 0);
}

void rgb2yuv::thread_x_2_fu_213_p2() {
    x_2_fu_213_p2 = (!x_reg_186.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(x_reg_186.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void rgb2yuv::thread_y_2_fu_264_p2() {
    y_2_fu_264_p2 = (!y_reg_197.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(y_reg_197.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void rgb2yuv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_208_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_259_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

