// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "advios.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic advios::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> advios::ap_const_lv1_0 = "0";
const sc_lv<32> advios::ap_const_lv32_1 = "1";
const sc_lv<1> advios::ap_const_lv1_1 = "1";
const sc_lv<4> advios::ap_const_lv4_0 = "0000";
const sc_lv<2> advios::ap_const_lv2_0 = "00";
const sc_logic advios::ap_const_logic_0 = sc_dt::Log_0;
const bool advios::ap_const_boolean_1 = true;

advios::advios(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_advios_controlLeds_fu_72 = new advios_controlLeds("grp_advios_controlLeds_fu_72");
    grp_advios_controlLeds_fu_72->ap_clk(clk);
    grp_advios_controlLeds_fu_72->ap_rst(reset);
    grp_advios_controlLeds_fu_72->ctrl(ctrl);
    grp_advios_controlLeds_fu_72->inSwitch(inSwitch);
    grp_advios_controlLeds_fu_72->outLeds(grp_advios_controlLeds_fu_72_outLeds);
    grp_advios_controlLeds_fu_72->outLeds_ap_vld(grp_advios_controlLeds_fu_72_outLeds_ap_vld);
    grp_advios_controlLeds_fu_72->count(count);
    grp_advios_makePulse_fu_88 = new advios_makePulse("grp_advios_makePulse_fu_88");
    grp_advios_makePulse_fu_88->ap_clk(clk);
    grp_advios_makePulse_fu_88->ap_rst(reset);
    grp_advios_makePulse_fu_88->count_i(count);
    grp_advios_makePulse_fu_88->count_o(grp_advios_makePulse_fu_88_count_o);
    grp_advios_makePulse_fu_88->count_o_ap_vld(grp_advios_makePulse_fu_88_count_o_ap_vld);

    SC_METHOD(thread_count);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_outLeds);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_advios_ssdm_threa_load_fu_104_p1);

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( clk.pos() );

    count = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "advios_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clk, "(port)clk");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, ctrl, "(port)ctrl");
    sc_trace(mVcdFile, inSwitch, "(port)inSwitch");
    sc_trace(mVcdFile, outLeds, "(port)outLeds");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, advios_ssdm_threa_load_fu_104_p1, "advios_ssdm_threa_load_fu_104_p1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, grp_advios_controlLeds_fu_72_outLeds, "grp_advios_controlLeds_fu_72_outLeds");
    sc_trace(mVcdFile, grp_advios_controlLeds_fu_72_outLeds_ap_vld, "grp_advios_controlLeds_fu_72_outLeds_ap_vld");
    sc_trace(mVcdFile, grp_advios_makePulse_fu_88_count_o, "grp_advios_makePulse_fu_88_count_o");
    sc_trace(mVcdFile, grp_advios_makePulse_fu_88_count_o_ap_vld, "grp_advios_makePulse_fu_88_count_o_ap_vld");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, count, "count");
#endif

    }
    mHdltvinHandle.open("advios.hdltvin.dat");
    mHdltvoutHandle.open("advios.hdltvout.dat");
}

advios::~advios() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_advios_controlLeds_fu_72;
    delete grp_advios_makePulse_fu_88;
}

void advios::thread_count() {
    if ( reset.read() == ap_const_logic_1) {
        count = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, grp_advios_makePulse_fu_88_count_o_ap_vld.read())) {
            count = grp_advios_makePulse_fu_88_count_o.read();
        }
    }
}

void advios::thread_outLeds() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_advios_controlLeds_fu_72_outLeds_ap_vld.read())) {
        outLeds = grp_advios_controlLeds_fu_72_outLeds.read();
    }
}

void advios::thread_advios_ssdm_threa_load_fu_104_p1() {
    advios_ssdm_threa_load_fu_104_p1 = ap_const_lv1_0;
}

void advios::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_const_lv2_0;
}

void advios::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void advios::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"reset\" :  \"" << reset.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ctrl\" :  \"" << ctrl.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inSwitch\" :  \"" << inSwitch.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"outLeds\" :  \"" << outLeds.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

